---
- name: Setup Nginx server on myserver list
  hosts: localhost
  become: True
  tasks:
    - name: Install the latest version of nginx
      command: amazon-linux-extras install nginx1.12=latest -y
      args:
        creates: /sbin/nginx

    - name: Start nginx
      service:
        name: nginx
        state: started

    - name: Enable nginx
      service:
        name: nginx
        enabled: yes

    - name: Ensure nginx is at the latest version
      command: nginx -v

    - name: Get status of nginx installed
      command: systemctl status nginx
   
    - name: comment out a line
      lineinfile:
        dest: /etc/nginx/nginx.conf
        regexp: ' (^include /etc/nginx/conf.d/*.conf)'
        line: '# (include /etc/nginx/conf.d/*.conf)'
        state: present
        
    - name: Copy nginx.conf file
      ansible.builtin.copy:
        src: /home/ansible
        dest: /etc/nginx/nginx.conf  
   
    - name: Recursively change ownership of a nginx directory
      ansible.builtin.file:
        path: /var/lib/nginx
        state: directory
        recurse: yes
        owner: nginx
        group: nginx

    - name: Enable nginx
      service:
        name: nginx
        enabled: yes

    - name: Start nginx
      service:
        name: nginx
        state: restarted
...
