---
- name: Setup Nginx server on myserver list
  hosts: localhost
  become: True
  tasks:
    - name: Install the latest version of nginx
      command: amazon-linux-extras install nginx1.12=latest -y
      args:
        creates: /sbin/nginx

    - name: Ensure nginx is at the latest version
      command: nginx -v

    - name: Get status of nginx installed
      command: systemctl status nginx
       
    - name: remove Default nginx.conf
      shell: rm -f /etc/ngnix/nginx.conf
        
    - name: Copy nginx.conf file
      shell: cp /home/ansible/nginx.conf /etc/nginx/nginx.conf

    - name: view the copied file (Nginx.conf)
      shell: cat /etc/nginx/nginx.conf
      register: output
    - debug:
        var: output

    - name: Recursively change ownership of a nginx directory
      ansible.builtin.file:
        path: /var/lib/nginx
        state: directory
        recurse: yes
        owner: nginx
        group: nginx

    - name: Enable nginx
      service:
        name: nginx
        enabled: yes

    - name: Start nginx
      service:
        name: nginx
        state: restarted
...
